services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: quinela-api
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    expose:
      - "5000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: quinela-nginx
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
